# Setup

Add libraries and configure with Drive

In [ ]:
from google.colab import drive
import pandas as pd
import xml.etree.ElementTree as ET
import os

drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

# PLABA Data Extraction and Cleanup

In [ ]:
import zipfile
import pandas as pd

zip_path = '/content/drive/MyDrive/Google 2F - FaithfulMed/FaithfulMed Data Simplifier/PLABA.zip'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content/plaba_unzipped')

train_df = pd.read_csv('/content/plaba_unzipped/train.csv')
val_df = pd.read_csv('/content/plaba_unzipped/val.csv')
test_df = pd.read_csv('/content/plaba_unzipped/test.csv')

plaba_df = pd.concat([train_df, val_df, test_df], ignore_index=True)

plaba_clean = plaba_df[['input_text', 'target_text']].copy()
plaba_clean.columns = ['Medical_Term', 'Lay_Language_Definiton']

plaba_clean['Metadata'] = plaba_df.apply(
    lambda row: {
        'source': 'PLABA',
        'pmid': str(row['pmid']),
        'question': row['question'],
        'adaptation_version': row['Adaptation_Version'],
        'question_type': row['Question_Type']
    }, axis=1
)

plaba_clean.head()

,Medical_Term,Lay_Language_Definiton,Metadata
0,Exercise-Associated Muscle Cramps (EAMC) are a...,Exercise-Associated Muscle Cramps (EAMC) are a...,"{'source': 'PLABA', 'pmid': '29857264', 'quest..."
1,"Background: Muscle cramp is a painful, involun...",Muscle cramps are unconscious contractions of ...,"{'source': 'PLABA', 'pmid': '33722257', 'quest..."
2,Muscle cramp is a temporary but intense and pa...,"Muscle cramp is a temporary but intense, painf...","{'source': 'PLABA', 'pmid': '31696455', 'quest..."
3,Muscular cramp is a common symptom in healthy ...,"Muscle cramps are common in healthy people, es...","{'source': 'PLABA', 'pmid': '30168894', 'quest..."
4,"Muscle cramps result in continuous, involuntar...",Muscle cramps cause constant and unintended co...,"{'source': 'PLABA', 'pmid': '29763070', 'quest..."

# MedLine Plus Glossary Extraction and Cleanup

In [ ]:
import xml.etree.ElementTree as ET
import pandas as pd
import zipfile
import os

medline_zip_path = '/content/drive/MyDrive/Google 2F - FaithfulMed/FaithfulMed Data Simplifier/MedLineGlossary.zip'
extract_folder = '/content/medline_unzipped'

with zipfile.ZipFile(medline_zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

xml_file_path = None
for root_dir, dirs, files in os.walk(extract_folder):
    for file in files:
        if file.endswith('.xml'):
            xml_file_path = os.path.join(root_dir, file)
            break
    if xml_file_path:
        break

if xml_file_path:
    tree = ET.parse(xml_file_path)
    root = tree.getroot()

    for elem in root.iter():
        if '}' in elem.tag:
            elem.tag = elem.tag.split('}', 1)[1]

    medline_records = []

    for topic in root.findall('.//health-topic'):
        # ONLY process English topics - we do not need spanish for now
        if topic.attrib.get('language') != 'English':
            continue

        term_title = topic.attrib.get('title', 'Unknown Term')
        summary_element = topic.find('.//full-summary')

        if summary_element is not None:
            summary_text = "".join(summary_element.itertext()).strip()

            if summary_text:
                medline_records.append({
                    'Medical_Term': term_title,
                    'Lay_Language_Definition': summary_text,
                    'Metadata': {
                        'source': 'MedlinePlus',
                        'url': topic.attrib.get('url', 'No URL')
                    }
                })

    medline_df = pd.DataFrame(medline_records)
    master_df = pd.concat([plaba_clean, medline_df], ignore_index=True)

    print(f"Added {len(medline_df)} English MedlinePlus records.")
    print(f"Total dictionary size so far: {len(master_df)}")

Added 1015 English MedlinePlus records.
Total dictionary size so far: 1936

# MedQuAd Extraction and Clean

In [ ]:
import os
import xml.etree.ElementTree as ET
import pandas as pd

# GitHub master folder
medquad_base = '/content/medquad_unzipped/MedQuAD-master'

medquad_records = []
xml_files_found = 0
qa_pairs_extracted = 0

print("Scanning MedQuAD folders for Q&A pairs...")

# go through every subfolder in MedQuAD-master
for root_dir, dirs, files in os.walk(medquad_base):
    for file in files:
        if file.endswith('.xml'):
            xml_files_found += 1
            file_path = os.path.join(root_dir, file)

            try:
                tree = ET.parse(file_path)
                root = tree.getroot()

                # main medical topic of the file
                focus_node = root.find('.//Focus')
                focus = focus_node.text if focus_node is not None else "Unknown"

                # Find every Question-Answer pair in the document
                for qa in root.findall('.//QAPair'):
                    question = qa.find('Question')
                    answer = qa.find('Answer')

                    if question is not None and answer is not None and answer.text:
                        qa_pairs_extracted += 1
                        medquad_records.append({
                            'Medical_Term': question.text.strip(),
                            'Lay_Language_Definition': answer.text.strip(),
                            'Metadata': {
                                'source': 'MedQuAD',
                                'topic_focus': focus
                            }
                        })
            except Exception as e:
                continue # skip any bad files

print(f"Diagnostics: Found {xml_files_found} XML files.")
print(f"Diagnostics: Extracted {qa_pairs_extracted} Q&A pairs.")

# Append new records to master dataframe
if qa_pairs_extracted > 0:
    medquad_df = pd.DataFrame(medquad_records)
    final_master_df = pd.concat([master_df, medquad_df], ignore_index=True)
    print(f"\nSUCCESS! Final dictionary size ready for embeddings: {len(final_master_df)}")
else:
    print("\nFAILURE: No Q&A pairs found.")

final_master_df.tail()

Scanning MedQuAD folders for Q&A pairs...
Diagnostics: Found 11274 XML files.
Diagnostics: Extracted 16407 Q&A pairs.

SUCCESS! Final dictionary size ready for embeddings: 18343

,Medical_Term,Lay_Language_Definiton,Metadata,Lay_Language_Definition
18338,What is (are) succinic semialdehyde dehydrogen...,NaN,"{'source': 'MedQuAD', 'topic_focus': 'succinic...",Succinic semialdehyde dehydrogenase deficiency...
18339,How many people are affected by succinic semia...,NaN,"{'source': 'MedQuAD', 'topic_focus': 'succinic...",Approximately 350 people with succinic semiald...
18340,What are the genetic changes related to succin...,NaN,"{'source': 'MedQuAD', 'topic_focus': 'succinic...",Mutations in the ALDH5A1 gene cause succinic s...
18341,Is succinic semialdehyde dehydrogenase deficie...,NaN,"{'source': 'MedQuAD', 'topic_focus': 'succinic...",This condition is inherited in an autosomal re...
18342,What are the treatments for succinic semialdeh...,NaN,"{'source': 'MedQuAD', 'topic_focus': 'succinic...",These resources address the diagnosis or manag...

# Embeddings.

 Uses batching to not exceed the limits of the free Google AI API rate limit. Results are saved in a JSONL file in the "FaithfulMed Data Simplifier" folder.

In [ ]:
#installls genAI library
!pip install -q -U google-generativeai

import google.generativeai as genai
from google.colab import userdata
import time
import json

GOOGLE_API_KEY = userdata.get('GEMINI_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)

# Combine Term and Definition for the embedding model
print("Preparing text for embeddings...")
final_master_df['Text_to_Embed'] = "Term: " + final_master_df['Medical_Term'].astype(str) + " | Definition: " + final_master_df['Lay_Language_Definition'].astype(str)

# Define where the final embeddings will be
output_file = '/content/drive/MyDrive/Google 2F - FaithfulMed/FaithfulMed Data Simplifier/RAG_Embeddings_Full.jsonl'
batch_size = 100
requests_per_minute = 14 # Slightly under 15 to meet limit
sleep_time = 60 / requests_per_minute

print(f"Starting batch processing. Total rows: {len(final_master_df)}")

# Process in chunks and write to Drive immediately
with open(output_file, 'a') as f:
    for i in range(0, len(final_master_df), batch_size):
        batch_df = final_master_df.iloc[i:i+batch_size].copy()
        text_list = batch_df['Text_to_Embed'].tolist()

        try:
            # Request embeddings for the whole batch
            response = genai.embed_content(
                model="models/text-embedding-004",
                content=text_list,
                task_type="retrieval_document"
            )

            # Attach vectors back to the chunk
            batch_df['Embedding'] = response['embedding']

            # Save progress line by line to JSONL format
            for _, row in batch_df.iterrows():
                f.write(row.to_json() + '\n')

            print(f"Successfully processed rows {i} to {i + len(batch_df) - 1}")

        except Exception as e:
            print(f"Error on rows {i} to {i + len(batch_df) - 1}: {e}")

        # pause for free API limits
        time.sleep(sleep_time)

print(f"\nEmbedding generation complete! File saved to {output_file}.")
print("It is now ready to hand off to Vaibhavi")

Preparing text for embeddings...
Starting batch processing. Total rows: 18343

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 335.78ms

Error on rows 0 to 99: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 234.73ms

Error on rows 100 to 199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 230.92ms

Error on rows 200 to 299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 255.82ms

Error on rows 300 to 399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 230.66ms

Error on rows 400 to 499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 258.23ms

Error on rows 500 to 599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 230.32ms

Error on rows 600 to 699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.62ms

Error on rows 700 to 799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 206.93ms

Error on rows 800 to 899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 284.08ms

Error on rows 900 to 999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 282.43ms

Error on rows 1000 to 1099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 259.98ms

Error on rows 1100 to 1199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 257.52ms

Error on rows 1200 to 1299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 257.64ms

Error on rows 1300 to 1399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 258.43ms

Error on rows 1400 to 1499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 231.59ms

Error on rows 1500 to 1599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 231.85ms

Error on rows 1600 to 1699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 231.72ms

Error on rows 1700 to 1799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 231.82ms

Error on rows 1800 to 1899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 258.59ms

Error on rows 1900 to 1999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 285.65ms

Error on rows 2000 to 2099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 289.26ms

Error on rows 2100 to 2199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 287.84ms

Error on rows 2200 to 2299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 286.55ms

Error on rows 2300 to 2399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 261.81ms

Error on rows 2400 to 2499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 257.90ms

Error on rows 2500 to 2599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 231.78ms

Error on rows 2600 to 2699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.19ms

Error on rows 2700 to 2799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.47ms

Error on rows 2800 to 2899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 181.11ms

Error on rows 2900 to 2999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 178.98ms

Error on rows 3000 to 3099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.57ms

Error on rows 3100 to 3199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.65ms

Error on rows 3200 to 3299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.41ms

Error on rows 3300 to 3399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.77ms

Error on rows 3400 to 3499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.05ms

Error on rows 3500 to 3599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.01ms

Error on rows 3600 to 3699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.25ms

Error on rows 3700 to 3799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 385.16ms

Error on rows 3800 to 3899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.41ms

Error on rows 3900 to 3999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.33ms

Error on rows 4000 to 4099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.61ms

Error on rows 4100 to 4199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 206.84ms

Error on rows 4200 to 4299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 230.90ms

Error on rows 4300 to 4399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.77ms

Error on rows 4400 to 4499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.88ms

Error on rows 4500 to 4599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.48ms

Error on rows 4600 to 4699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 206.11ms

Error on rows 4700 to 4799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 181.32ms

Error on rows 4800 to 4899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.60ms

Error on rows 4900 to 4999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.15ms

Error on rows 5000 to 5099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.28ms

Error on rows 5100 to 5199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.26ms

Error on rows 5200 to 5299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.90ms

Error on rows 5300 to 5399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.52ms

Error on rows 5400 to 5499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 206.77ms

Error on rows 5500 to 5599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 206.33ms

Error on rows 5600 to 5699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 232.59ms

Error on rows 5700 to 5799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 231.49ms

Error on rows 5800 to 5899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 232.04ms

Error on rows 5900 to 5999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 209.11ms

Error on rows 6000 to 6099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 208.50ms

Error on rows 6100 to 6199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.58ms

Error on rows 6200 to 6299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 231.70ms

Error on rows 6300 to 6399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 260.11ms

Error on rows 6400 to 6499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 230.87ms

Error on rows 6500 to 6599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.38ms

Error on rows 6600 to 6699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 231.90ms

Error on rows 6700 to 6799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.46ms

Error on rows 6800 to 6899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 261.81ms

Error on rows 6900 to 6999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 258.21ms

Error on rows 7000 to 7099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 257.64ms

Error on rows 7100 to 7199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 259.52ms

Error on rows 7200 to 7299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 258.86ms

Error on rows 7300 to 7399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 263.63ms

Error on rows 7400 to 7499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.65ms

Error on rows 7500 to 7599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.17ms

Error on rows 7600 to 7699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.84ms

Error on rows 7700 to 7799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 230.24ms

Error on rows 7800 to 7899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 230.58ms

Error on rows 7900 to 7999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 206.54ms

Error on rows 8000 to 8099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.33ms

Error on rows 8100 to 8199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.07ms

Error on rows 8200 to 8299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 206.58ms

Error on rows 8300 to 8399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 206.17ms

Error on rows 8400 to 8499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.97ms

Error on rows 8500 to 8599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.80ms

Error on rows 8600 to 8699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.83ms

Error on rows 8700 to 8799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 206.48ms

Error on rows 8800 to 8899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.17ms

Error on rows 8900 to 8999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.83ms

Error on rows 9000 to 9099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.69ms

Error on rows 9100 to 9199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 206.63ms

Error on rows 9200 to 9299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.86ms

Error on rows 9300 to 9399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 206.33ms

Error on rows 9400 to 9499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.98ms

Error on rows 9500 to 9599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.96ms

Error on rows 9600 to 9699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.74ms

Error on rows 9700 to 9799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 206.39ms

Error on rows 9800 to 9899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.02ms

Error on rows 9900 to 9999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 255.61ms

Error on rows 10000 to 10099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.79ms

Error on rows 10100 to 10199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.89ms

Error on rows 10200 to 10299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.60ms

Error on rows 10300 to 10399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.90ms

Error on rows 10400 to 10499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.40ms

Error on rows 10500 to 10599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.07ms

Error on rows 10600 to 10699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.98ms

Error on rows 10700 to 10799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.88ms

Error on rows 10800 to 10899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.04ms

Error on rows 10900 to 10999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 181.48ms

Error on rows 11000 to 11099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.20ms

Error on rows 11100 to 11199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.46ms

Error on rows 11200 to 11299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.92ms

Error on rows 11300 to 11399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 230.20ms

Error on rows 11400 to 11499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 206.76ms

Error on rows 11500 to 11599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.02ms

Error on rows 11600 to 11699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.76ms

Error on rows 11700 to 11799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.66ms

Error on rows 11800 to 11899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.12ms

Error on rows 11900 to 11999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 182.19ms

Error on rows 12000 to 12099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.27ms

Error on rows 12100 to 12199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 155.08ms

Error on rows 12200 to 12299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.55ms

Error on rows 12300 to 12399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.24ms

Error on rows 12400 to 12499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.29ms

Error on rows 12500 to 12599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.17ms

Error on rows 12600 to 12699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.22ms

Error on rows 12700 to 12799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.08ms

Error on rows 12800 to 12899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 153.99ms

Error on rows 12900 to 12999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 153.86ms

Error on rows 13000 to 13099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.56ms

Error on rows 13100 to 13199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 155.26ms

Error on rows 13200 to 13299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.50ms

Error on rows 13300 to 13399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 153.85ms

Error on rows 13400 to 13499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 153.93ms

Error on rows 13500 to 13599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 153.88ms

Error on rows 13600 to 13699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 155.11ms

Error on rows 13700 to 13799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 184.44ms

Error on rows 13800 to 13899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.23ms

Error on rows 13900 to 13999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.14ms

Error on rows 14000 to 14099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.02ms

Error on rows 14100 to 14199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 182.45ms

Error on rows 14200 to 14299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.89ms

Error on rows 14300 to 14399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.26ms

Error on rows 14400 to 14499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.40ms

Error on rows 14500 to 14599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 155.94ms

Error on rows 14600 to 14699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.59ms

Error on rows 14700 to 14799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 155.13ms

Error on rows 14800 to 14899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.12ms

Error on rows 14900 to 14999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.34ms

Error on rows 15000 to 15099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.38ms

Error on rows 15100 to 15199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.35ms

Error on rows 15200 to 15299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.65ms

Error on rows 15300 to 15399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.93ms

Error on rows 15400 to 15499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.61ms

Error on rows 15500 to 15599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.00ms

Error on rows 15600 to 15699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.41ms

Error on rows 15700 to 15799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.36ms

Error on rows 15800 to 15899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.44ms

Error on rows 15900 to 15999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.17ms

Error on rows 16000 to 16099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.26ms

Error on rows 16100 to 16199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 153.93ms

Error on rows 16200 to 16299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.35ms

Error on rows 16300 to 16399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.47ms

Error on rows 16400 to 16499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 153.69ms

Error on rows 16500 to 16599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.04ms

Error on rows 16600 to 16699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.39ms

Error on rows 16700 to 16799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 204.63ms

Error on rows 16800 to 16899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 207.01ms

Error on rows 16900 to 16999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.85ms

Error on rows 17000 to 17099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.01ms

Error on rows 17100 to 17199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.25ms

Error on rows 17200 to 17299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 155.20ms

Error on rows 17300 to 17399: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 155.49ms

Error on rows 17400 to 17499: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.81ms

Error on rows 17500 to 17599: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.35ms

Error on rows 17600 to 17699: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 205.25ms

Error on rows 17700 to 17799: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.10ms

Error on rows 17800 to 17899: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 179.41ms

Error on rows 17900 to 17999: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 155.65ms

Error on rows 18000 to 18099: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 180.46ms

Error on rows 18100 to 18199: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.76ms

Error on rows 18200 to 18299: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

WARNING:tornado.access:400 POST /v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint (::1) 154.35ms

Error on rows 18300 to 18342: 400 POST https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.

Embedding generation complete! File saved to /content/drive/MyDrive/Google 2F - FaithfulMed/FaithfulMed Data Simplifier/RAG_Embeddings_Full.jsonl.
It is now ready to hand off to Vaibhavi for ChromaDB ingestion.

# Processing

In [ ]:
import